name: rick_and_morty_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^3.0.2
  material_design_icons_flutter: ^6.0.7096
  path_provider: ^2.0.11
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.2 
  build_runner: ^2.1.2
  hive_generator: ^1.1.3
  test:
  mockito: ^5.3.2
  faker:

flutter:

  uses-material-design: true

